# iOS CMake Toolchain
set(CMAKE_SYSTEM_NAME iOS)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_OSX_DEPLOYMENT_TARGET "14.0" CACHE STRING "iOS Deployment Target")
set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "iOS Architecture")
set(CMAKE_OSX_SYSROOT "iphoneos" CACHE STRING "iOS SDK")

set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO)
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE NO)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_MACOSX_BUNDLE_GUI_IDENTIFIER "com.krkr.sync")
set(CMAKE_MACOSX_BUNDLE_NAME "KRKR Sync")
